var func = function (binding, options) {
  const nex1 = new (WX.Button ? WX.Button : WX.Element)("nex1_", options);
  nex1.setAttribute("id", "nex1");
  const nex2 = new (WX.Button ? WX.Button : WX.Element)("nex2_", options);
  nex2.setAttribute("id", "nex2");
  const nex3 = new (WX.Button ? WX.Button : WX.Element)("nex3_", options);
  nex3.setAttribute("id", "nex3");
  const nex4 = new (WX.Button ? WX.Button : WX.Element)("nex4_", options);
  nex4.setAttribute("id", "nex4");
  const nex5 = new (WX.Button ? WX.Button : WX.Element)("nex5_", options);
  nex5.setAttribute("id", "nex5");
  const nex6 = new (WX.Button ? WX.Button : WX.Element)("nex6_", options);
  nex6.setAttribute("id", "nex6");
  const nex7 = new (WX.Button ? WX.Button : WX.Element)("nex7_", options);
  nex7.setAttribute("id", "nex7");
  nex1.setAttribute("type", "primary");
  nex1.setText(`1.页面主操作`);
  nex2.setAttribute("type", "primary");
  nex2.setAttribute("loading", true);
  nex2.setText(`2. 页面主操作`);
  nex3.setAttribute("type", "primary");
  nex3.setAttribute("disabled", true);
  nex3.setText(`3. 页面主操作`);
  nex4.setAttribute("type", "default");
  nex4.setText(`4. 页面次要操作`);
  nex5.setAttribute("type", "default");
  nex5.setAttribute("disabled", true);
  nex5.setText(`5. 页面次要操作`);
  nex6.setAttribute("type", "warn");
  nex6.setText(`6. 警告类操作`);
  nex7.setAttribute("type", "warn");
  nex7.setAttribute("disabled", true);
  nex7.setText(`7. 警告类操作`);
  return [nex1, nex2, nex3, nex4, nex5, nex6, nex7];
};
func;
